### ISSUE TITLE
wifi transmission time

### ISSUE THREAD

**Issue by danielec1980** [3KUdelta/Solar_WiFi_Weather_Station#19]
Hi,
I positioned the weather station a little far from the router and often cannot connect to the router.
it's possible to lengthen the time of transmission to the router before it goes out of timeout?

**Comment by f45tb00t** [comment]
Hello danielec1980,

sorry but I do not get the point in doing so. The ESP tries to establish the connection, no matter, as far as I can see, about the latency. 

I assume, that even the 4 way handshake is not working properly, as well getting an IP address via DHCP. So this means the connection will never be established correctly.

I used an outdoor weatherstation which was placed in the garden before. I guess something between 10 and 20 meters far from my router. One wall was between the line of sight and as well a small tree/bush. And take into account I did not move the 0 ohm resistor at all. I used the internal antenna all the time. 

So I suggest improve your wifi connection. Also did you "move" the 0 ohm resistor to use the external antenna? Because if you do not move this, the external antenna port is not gonna work at all. If you moved it, have you compared the wifi signal before and after? Means check which APs are in range with internal antenna, move the resistor and compare the results? Because you should have seen more.


Cheers

fastboot
